# Generated by Django 3.2.9 on 2021-11-30 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('exact_address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathroom_type', models.CharField(choices=[('Attached Bathroom', 'Attached'), ('Shared Bathroom', 'Common')], default='Attached Bathroom', max_length=20)),
                ('no_bathrooms', models.IntegerField()),
                ('max_acomodation', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Air Conditioner', 'Ac'), ('No Air Conditioner', 'No Ac')], default='Air Conditioner', max_length=25)),
                ('main_photo', models.ImageField(upload_to='room_images/')),
                ('photo_1', models.ImageField(upload_to='room_images/')),
                ('photo_2', models.ImageField(upload_to='room_images/')),
                ('photo_3', models.ImageField(upload_to='room_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.roomlocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
