# Generated by Django 3.2.9 on 2021-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
