# Generated by Django 3.2.9 on 2021-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=2),
        ),
    ]
