# Generated by Django 3.2.9 on 2021-12-03 03:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedroom_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Queen', 'Queen'), ('King', 'King'), ('Twin', 'Twin'), ('Double-Double', 'Double Double'), ('NIL', 'Nil')], default='NIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(default='default_room.jpg', upload_to='room_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(default='default_room.jpg', upload_to='room_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(default='default_room.jpg', upload_to='room_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(default='default_room.jpg', upload_to='room_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'bedroom_type', 'bathroom_type', 'room_type']),
        ),
    ]
