# Generated by Django 3.2.9 on 2021-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20211222_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bedroom_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchen_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchen_description',
            field=models.TextField(default='ABC'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Apartement', 'Apartement')], default='Room', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
