# Generated by Django 3.2.9 on 2021-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20211225_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_progres',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CHECKED IN', 'Checked In'), ('CHECKED OUT', 'Checked Out'), ('CANCLLED', 'Canclled')], default='BOOKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='kitchen_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Apartement', 'Apartement'), ('Full House', 'House')], default='Room', max_length=20),
        ),
    ]
