# Generated by Django 3.2.9 on 2021-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20211225_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone_Number', models.CharField(blank=True, max_length=10)),
                ('Message', models.TextField()),
            ],
        ),
    ]
