# Generated by Django 3.2.9 on 2022-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20211230_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_progres',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
