# Generated by Django 3.2.9 on 2022-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20220105_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_host_email',
            field=models.EmailField(max_length=100),
        ),
    ]
