# Generated by Django 3.2.9 on 2022-01-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_booking_room_host_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_host_phone',
            field=models.IntegerField(default='0'),
        ),
    ]
