# Generated by Django 3.2.9 on 2022-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_booking_room_host_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_host_phone',
            field=models.IntegerField(),
        ),
    ]
