# Generated by Django 3.2.9 on 2022-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_booking_room_host_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_exact_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sum_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
