# Generated by Django 3.2.9 on 2022-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20220105_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_exact_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_full_name',
            field=models.CharField(max_length=100),
        ),
    ]
