# Generated by Django 3.2.9 on 2022-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_auto_20220105_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='idx',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_exact_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_host_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_host_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sum_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
