# Generated by Django 3.2.9 on 2022-01-05 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_auto_20220105_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='idx',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_city',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_exact_address',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_host_email',
            field=models.EmailField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_host_phone',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sum_amount',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_full_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(editable=False),
        ),
    ]
