# Generated by Django 3.2.9 on 2022-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_auto_20220105_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_host_fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_host_id',
            field=models.IntegerField(default=0),
        ),
    ]
