# Generated by Django 3.2.9 on 2022-01-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_alter_booking_date_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
