# Generated by Django 3.2.9 on 2022-01-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_booking_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('service_charge_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('refund_completed', models.BooleanField(default=False)),
                ('booking_staus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.booking')),
            ],
        ),
    ]
