# Generated by Django 3.2.9 on 2022-01-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_refund_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_control',
            name='refund_percentage',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
