# Generated by Django 3.2.9 on 2022-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_alter_booking_room_host_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
