# Generated by Django 3.2.9 on 2022-01-20 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_alter_booking_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
