# Generated by Django 3.2.9 on 2022-01-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_auto_20220120_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
