# Generated by Django 3.2.9 on 2022-01-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_auto_20220120_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['check_in']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['approved']},
        ),
        migrations.AlterModelOptions(
            name='refund_control',
            options={'ordering': ['refund_completed']},
        ),
    ]
