# Generated by Django 3.2.9 on 2022-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_alter_listing_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
