# Generated by Django 3.2.9 on 2022-01-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_title',
        ),
    ]
