# Generated by Django 3.2.9 on 2022-01-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
