# Generated by Django 3.2.9 on 2022-01-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0044_alter_booking_refund_status'),
        ('notification', '0007_alter_notification_notification_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='The_one_who_is_booking_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='The_room_booked', to='listings.listing'),
        ),
    ]
