# Generated by Django 3.2.9 on 2022-01-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
    ]
