# Generated by Django 3.2.9 on 2022-01-08 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_rateguests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateGuests',
            new_name='RateGuest',
        ),
    ]
