# Generated by Django 3.2.9 on 2021-12-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxes',
            new_name='Taxe',
        ),
    ]
